name: Validar Secrets

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Permite ejecución manual

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Instalar dependencias (si necesitas más)
      run: |
        python -m pip install --upgrade pip
    
    - name: Ejecutar validación de secrets
      run: |
        python validate_secrets.py
      env:
        BEARER_TOKEN_1: ${{ secrets.BEARER_TOKEN_1 }}
        BEARER_TOKEN_2: ${{ secrets.BEARER_TOKEN_2 }}
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
    
    - name: Reportar éxito/fallo
      if: failure()
      run: echo "¡Fallo en la validación! Verifica los secrets."
